name: psicoajuda
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_hooks: ^0.18.0
  provider: ^6.0.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_database: ^10.2.3
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.0-alpha.5
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.1.1
  flutter_login: ^4.1.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  # modular_test: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/psicoAjuda.png
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
