// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6dIkowMCeyRIX3sM3yD4xlkzn24k7BjU',
    appId: '1:983748320031:web:b809504598f01056236e2a',
    messagingSenderId: '983748320031',
    projectId: 'psicoajuda-3b5e9',
    authDomain: 'psicoajuda-3b5e9.firebaseapp.com',
    storageBucket: 'psicoajuda-3b5e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ig0qEmgBuVH96l39jL9VBRDPzIwOJO0',
    appId: '1:983748320031:android:0a365173848ca5fa236e2a',
    messagingSenderId: '983748320031',
    projectId: 'psicoajuda-3b5e9',
    storageBucket: 'psicoajuda-3b5e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyGNqlNJzY1pNxcQnlJ5XuRbLaw36wTYE',
    appId: '1:983748320031:ios:ee60dbcf54d29142236e2a',
    messagingSenderId: '983748320031',
    projectId: 'psicoajuda-3b5e9',
    storageBucket: 'psicoajuda-3b5e9.appspot.com',
    iosClientId: '983748320031-286pb1cte50vqti8jkvcd5ki6ik9q5u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.psicoajuda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyGNqlNJzY1pNxcQnlJ5XuRbLaw36wTYE',
    appId: '1:983748320031:ios:ee60dbcf54d29142236e2a',
    messagingSenderId: '983748320031',
    projectId: 'psicoajuda-3b5e9',
    storageBucket: 'psicoajuda-3b5e9.appspot.com',
    iosClientId: '983748320031-286pb1cte50vqti8jkvcd5ki6ik9q5u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.psicoajuda',
  );
}
